### ISSUE TITLE
laravel 6.*下貌似切换语言无效

### ISSUE THREAD

**Issue by ygcool** [laravel-admin-extensions/multi-language#4]
请问什么时候能支持一下laravel6.*呢？

**Comment by tarikhh** [comment]
Didn't know what you did type but for me to make it working on Laravel 6.

I tested to use Request in Place if Input :

Replaced on file : 
_vendor/laravel-admin-extensions/multi-language/src/Http/Controllers/MultiLanguageController.php_

`//use Illuminate\Support\Facades\Input;`
**with**
`use Illuminate\Http\Request;`

...
```
//    public function locale() {
//        $locale = Input::get('locale');
```
**with**
```
    public function locale(Request $request) {
        $locale = $request->locale;
```

Seems working Languages can be switched.
